// app/layout.tsx
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import localfont from "next/font/local";
import "./globals.css";
import SplashScreen from "./components/SplashScreen";
import BackgroundVideo from "./components/BackgroundVideo"; 
import Logo from "./components/Logo";
import MarqueeBanner from "./components/MarqueeBanner";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  display: "swap",
});

const RawPixel = localfont({
  src: [
    {
      path: "../../public/fonts/RawPixel.ttf",
      weight: "400",
    },
  ],
  variable: "--raw-pixel",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   const marqueeText = "OPERATING SYSTEM FOR AI AGENTS";
  return (
    <html lang="en" className={outfit.variable}>
      <body className={`${outfit.variable} ${RawPixel.variable} antialiased bg-[#0a0a0a] relative w-screen h-screen overflow-hidden`}>
        <BackgroundVideo /> 
        <MarqueeBanner text={marqueeText} />
        <Logo />
        <SplashScreen>
        {children}

        </SplashScreen>
          
        
      </body>
    </html>
  );
}
