// app/layout.tsx (App Router layout)
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import localfont from "next/font/local";
import "./globals.css";
import SplashScreen from "./components/SplashScreen";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  display: "swap",
});

const RawPixel = localfont({
  src: [
    {
      path: "../../public/fonts/RawPixel.ttf",
      weight: "400",
    },
  ],
  variable: "--raw-pixel",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={outfit.variable}>
      <body className={`${outfit.variable} ${RawPixel.variable} antialiased`}>
        <SplashScreen>
          {children}
        </SplashScreen>
      </body>
    </html>
  );
}
